name: Automatic Merge back
on:
  push:
    branches:
      - "*"
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get merged releases
        id: merged-releases
        run: |
          git fetch --all
          git branch --merged main > merged-releases.csv
          git branch > b.txt
          echo ">>>>>>>1"
          cat merged-releases.csv
          echo ">>>>>>>2"
          cat b.txt
          echo ">>>>>>>3"

        shell: bash
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/mergeback.js')
            await script({github, context, core})
