name: Automatic Merge Back
on:
  push:
    branches:
      - "main"

jobs:
  mergeback:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Get unmerged releases
        id: merged-releases
        run: |
          git branch -a --no-merged main | grep origin/release | sed 's/remotes\/origin\///' > no-merged-releases.txt || true
        shell: bash
      - name: Create mergeback PRs
        uses: actions/github-script@v6
        env:
          # CI_USER: kendlee
        with:
          script: |
            const script = require('./.github/workflows/mergeback.js')
            await script({github, context, core}, process.env)
