on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - env:
          GH: ${{ toJson(github) }}
        run: |
          echo "$GH"
      # - uses: actions/checkout@v2
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const script = require('./.github/workflows/mergeback.js')
      #       await script({github, context, core})
